name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "ibc-rollup" ]
  pull_request:
    branches: [ "ibc-rollup" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SOVEREIGN_SDK_PRIVATE_SSH_KEY }}
      - uses: actions/checkout@v4
        with:
          submodules: true
          ssh-key: ${{ secrets.SOVEREIGN_SDK_PRIVATE_SSH_KEY }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.2"
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-risc0 # Risc0 v0.17 and higher require a cargo extension to build the guest code
        run: cargo install cargo-risczero
      - name: Install risc0-zkvm toolchain # Use the risc0 cargo extension to install the risc0 std library for the current toolchain
        run: cargo risczero install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Run README.md
        run: chmod +x sov-rollup-starter.sh && ./sov-rollup-starter.sh
